name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install flet
        pip install fastapi
        pip install mysqlclient
        #pip install --upgrade autopep8
    - name: Analysing the code with pylint
      run: |
        #autopep8 --in-place --aggressive --recursive Calendar.py main.py
        pylint -j 0 $(git ls-files 'main.py') --recursive=y
